version: 2

models:

    - name: sales
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: PK-identificador de ordenes
            tests : 
            - not_null 

          - name: products_id
            description: identificador de producto
            tests : 
            - not_null    

          - name: qty
             
          - name: turnover
            description: ganancias totales por ventas
            tests : 
            - not_null  

          - name: purchase_cost
            description: costos asociados a las ventas
            tests : 
            - not_null 

          - name: margin
            description: ganancias-costos